### PR TITLE
more types, CORDIC, drop numtoa-style formatting

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7761de2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7761de2 with merge 7761de2...

**Comment by japaric** [comment]
@homunkulus r-

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 29cc988 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 29cc988 with merge 29cc988...

**Pull request merged**
